displayName: Bulk Redirects
type: middleware
iconPath: .assets/icon.png

import: github.com/shufanshijie/traefik-bulk-redirects

summary: Middleware for Cloudflare-style bulk redirects.

testData:
  redirects:
    - sourceURL: https://example.com/premium/coupon
      targetURL: https://example.com/en/premium/
      statusCode: 302
      preserveQueryString: true
      subpathMatching: false

    - sourceURL: https://example.com/docs
      targetURL: https://example.com/en/resources
      statusCode: 301
      preserveQueryString: true
      subpathMatching: true
